@namespace
class SpriteKind:
    question = SpriteKind.create()
    question2 = SpriteKind.create()
    empoweredPlayer = SpriteKind.create()
    dougenentrence = SpriteKind.create()

def on_overlap_tile(sprite, location):
    global questionbox, questionbo_x
    questionbox = sprites.create(img("""
            . . . . . . . . . . . . . . . . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e d d d d d d d d d d e e . 
                    . e e d f d d d f d f d d e e . 
                    . e e f d f d f f f f d d e e . 
                    . e e d f d d d f d d d d e e . 
                    . e e d f f d f d d d d d e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e .
        """),
        SpriteKind.question)
    questionbox.set_position(95, 119)
    questionbo_x = sprites.create(img("""
            . . . . . . . . . . . . . . . . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e d d d d d d d d d d e e . 
                    . e e d f d d d f d f d d e e . 
                    . e e f d f d f f f f d d e e . 
                    . e e d f d d d f d d d d e e . 
                    . e e d f f d f d d d d d e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e . 
                    . e e e e e e e e e e e e e e .
        """),
        SpriteKind.question2)
    questionbo_x.set_position(95, 79)
    tiles.set_current_tilemap(tilemap2[0])
    tiles.place_on_random_tile(_1st_sprrite, sprites.dungeon.stair_south)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.stair_north,
    on_overlap_tile)

def on_on_overlap(sprite2, otherSprite):
    game.show_long_text("Greetings! Do you want to go into the hell of dogends",
        DialogLayout.BOTTOM)
    story.show_player_choices("Yes I am ready", "Give me some time")
    if story.check_last_answer("Yes I am ready"):
        tiles.set_current_tilemap(tilemap2[3])
        sprites.destroy(doungenentrence)
        fightScene(sprite2)
    else:
        game.show_long_text("Okay have some time then", DialogLayout.CENTER)
sprites.on_overlap(SpriteKind.empoweredPlayer,
    SpriteKind.dougenentrence,
    on_on_overlap)

def on_overlap_tile2(sprite3, location2):
    game.show_long_text("You may no longer enter", DialogLayout.CENTER)
    pause(500)
scene.on_overlap_tile(SpriteKind.empoweredPlayer,
    sprites.dungeon.stair_north,
    on_overlap_tile2)

def on_on_overlap2(sprite4, otherSprite2):
    game.show_long_text("How did you get here?", DialogLayout.BOTTOM)
    story.show_player_choices("I went down the stairs", "Why do you need to know?")
    game.show_long_text("Well, you came here at the right time I guess. ",
        DialogLayout.BOTTOM)
    game.show_long_text("this is a place that you get your super power",
        DialogLayout.BOTTOM)
    sprites.destroy(otherSprite2)
sprites.on_overlap(SpriteKind.player, SpriteKind.question, on_on_overlap2)

def earthCommonSpell2():
    global projectileearth
    animation.run_image_animation(earthwizard,
        [img("""
                ........................
                        ........................
                        ........................
                        ..........ffff..........
                        ........fff77fff........
                        .......fff7887fff.......
                        ......fff787787fff......
                        ......ff778778777f......
                        ......f77ffffff77f......
                        ......ffffeeeeffff......
                        .....ffefbf44fbfeff.....
                        .....fee41fddf14eef.....
                        .....ffeeddddddeeff7....
                        ....7..fee4444eef..7....
                        ....7777f788887f7777....
                        ....7777f788887f7777....
                        ........f775577f77......
                        .........ffffff.........
                        .........ff..ff.........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        .........ffffff.........
                        ........f7f7777ff.......
                        .......f77777777ff......
                        ..cc...f7877f8777f......
                        ..c7c.f7788888ffff......
                        ..c77cf77ffff7777f......
                        ...c77cffeeefffffff.....
                        ....c88c444fbe44eff.....
                        .....c8c4ddf14d4eef.....
                        .....ccc4eddd4eeef......
                        ......8888e44eeff.......
                        .......88888888f........
                        ........f878887f........
                        ........f877777f........
                        .........ffffff.........
                        ...........fff..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........fff..........
                        ..........f7fffff.......
                        ........ff7777777ff.....
                        .......ff787778777ff....
                        .......f77888887777f....
                        ......f77777777fffff....
                        ......f77fffff7777fff...
                        c.....fffeeefffffffff...
                        7cc...fee44fbbe44efef...
                        c78cc..feddfbb4d4eef....
                        .c888c888888888888f.....
                        ..c88c88887888878f......
                        ...ccc88887777778f......
                        ......8888ffffffff......
                        ..........ff...fff......
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ...............ff.......
                        .............ff7ffff....
                        ............ff7f7777ff..
                        ...........ff77f77777ff.
                        ...........f7777777777f.
                        ..........f7777777fffff.
                        ..........f77ffff7777fff
                        ..........fffeeeffffffff
                        ..........fee44fbe44efef
                        ...........feddfb4d4eef.
                        ..........c.eeddd4eeef..
                        ....ccccccc888788878f...
                        ....777888c888777778f...
                        ......ccccc.8888fffff...
                        ..........c...ffffffff..
                        ...............ff..fff..
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........fff..........
                        ..........f7fffff.......
                        ........ff7777777ff.....
                        .......ff777777777ff....
                        .......f7777fff7777f....
                        ......f77777777fffff....
                        ......f77fffff7777fff...
                        c.....fffeeefffffffff...
                        7cc...fee44fbbe44efef...
                        c78cc..feddfbb4d4eef....
                        .c888c888888888888f.....
                        ..c88c88878888878f......
                        ...ccc88877777778f......
                        ......8888ffffffff......
                        ..........ff...fff......
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        .........ffffff.........
                        ........f7f7777ff.......
                        .......f77777777ff......
                        ..cc...f787778777f......
                        ..c7c.f7788888ffff......
                        ..c77cf77ffff7777f......
                        ...c77cffeeefffffff.....
                        ....c88c444fbe44eff.....
                        .....c8c4ddf14d4eef.....
                        .....ccc4eddd4eeef......
                        ......8888e44eeff.......
                        .......88888888f........
                        ........f878878f........
                        ........f877778f........
                        .........ffffff.........
                        ...........fff..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ffff..........
                        ........fff77fff........
                        .......fff7887fff.......
                        ......fff787787fff......
                        ......ff778778777f......
                        ......f77ffffff77f......
                        ......ffffeeeeffff......
                        .....ffefbf44fbfeff.....
                        .....fee41fddf14eef.....
                        .....ffeeddddddeeff7....
                        ....7..fee4444eef..7....
                        ....7777f788887f7777....
                        ....7777f788887f7777....
                        ........f775577f77......
                        .........ffffff.........
                        .........ff..ff.........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """)],
        200,
        False)
    pause(500)
    projectileearth = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . 7 7 7 7 7 7 7 7 7 7 7 . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        firewizard,
        -100,
        0)
def spriteController(mySprite: Sprite):
    controller.move_sprite(mySprite)
    scene.camera_follow_sprite(mySprite)
    mySprite.set_flag(SpriteFlag.STAY_IN_SCREEN, True)
def fightScene(mySprite2: Sprite):
    tiles.place_on_tile(mySprite2, tiles.get_tile_location(19, 5))

def on_on_overlap3(sprite5, otherSprite3):
    game.show_long_text("CHOOSE YOUR POWER", DialogLayout.BOTTOM)
    story.show_player_choices("Fire", "Ice", "Earth")
    if story.check_last_answer("Fire"):
        tiles.place_on_random_tile(_1st_sprrite, sprites.dungeon.collectible_red_crystal)
    elif story.check_last_answer("Ice"):
        tiles.place_on_random_tile(_1st_sprrite, sprites.dungeon.collectible_insignia)
    elif story.check_last_answer("Earth"):
        tiles.place_on_random_tile(_1st_sprrite, sprites.dungeon.collectible_blue_crystal)
sprites.on_overlap(SpriteKind.player, SpriteKind.question2, on_on_overlap3)

def earthwizard2():
    global earthwizard
    earthwizard = sprites.create(img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f f 7 7 f f f . . . . 
                    . . . f f f 7 8 8 7 f f f . . . 
                    . . f f f 7 8 7 7 8 7 f f f . . 
                    . . f f 7 7 8 7 7 8 7 7 7 f . . 
                    . . f 7 7 f f f f f f 7 7 f . . 
                    . . f f f f e e e e f f f f . . 
                    . f f e f b f 4 4 f b f e f f . 
                    . f e e 4 1 f d d f 1 4 e e f . 
                    . f f e e d d d d d d e e f f 7 
                    7 . . f e e 4 4 4 4 e e f . . 7 
                    7 7 7 7 f 7 8 8 8 8 7 f 7 7 7 7 
                    7 7 7 7 f 7 8 8 8 8 7 f 7 7 7 7 
                    . . . . f 7 7 5 5 7 7 f 7 7 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """),
        SpriteKind.empoweredPlayer)
    spriteController(earthwizard)

def on_on_overlap4(sprite6, otherSprite4):
    color.start_fade(color.original_palette, color.black, 500)
    tiles.place_on_tile(sprite6, tiles.get_tile_location(10, 5))
    tiles.place_on_tile(otherSprite4, tiles.get_tile_location(8, 5))
    otherSprite4.follow(sprite6, 0)
    fightscene12(sprite6)
    color.start_fade(color.black, color.original_palette, 500)
sprites.on_overlap(SpriteKind.empoweredPlayer, SpriteKind.enemy, on_on_overlap4)

def on_overlap_tile3(sprite7, location3):
    spriteCreator("abc")
    afterpower(earthwizard)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_blue_crystal,
    on_overlap_tile3)

def spriteCreator(text: str):
    if text == "fire":
        firewizard2()
    elif text == "ice":
        icewizard2()
    else:
        earthwizard2()
def fightscene12(mySprite3: Sprite):
    tiles.place_on_tile(mySprite3, tiles.get_tile_location(13, 5))
    controller.move_sprite(mySprite3, 0, 0)
    tiles.place_on_tile(Firstenemy, tiles.get_tile_location(9, 5))
    Firstenemy.follow(mySprite3, 0)
def firewizard2():
    global firewizard
    firewizard = sprites.create(img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f f 2 2 f f f . . . . 
                    . . . f f f 2 2 2 2 f f f . . . 
                    . . f f f 2 2 2 2 2 2 f f f . . 
                    . . f f 2 2 2 2 2 2 2 2 2 f . . 
                    . . f 2 2 f f f f f f 2 2 f . . 
                    . . f f f f e e e e f f f f . . 
                    . f f e f b f 4 4 f b f e f f . 
                    . f e e 4 1 f d d f 1 4 e e f . 
                    . f f e e d d d d d d e e f f 2 
                    2 . . f e e 4 4 4 4 e e f . . 2 
                    2 2 2 2 f 2 2 2 2 2 2 f 2 2 2 2 
                    2 2 2 2 f 2 2 2 2 2 2 f 2 2 2 2 
                    . . . . f 2 2 5 5 2 2 f 2 2 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """),
        SpriteKind.empoweredPlayer)
    spriteController(firewizard)
def afterpower(mySprite4: Sprite):
    global doungenentrence
    sprites.destroy(_1st_sprrite)
    sprites.destroy(questionbo_x)
    sprites.destroy(questionbox)
    tiles.set_current_tilemap(tilemap2[2])
    tiles.place_on_tile(mySprite4, tiles.get_tile_location(5, 9))
    doungenentrence = sprites.create(img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f f a a f f f . . . . 
                    . . . f f f a a a a f f f . . . 
                    . . f f f a a a a a a a f f . . 
                    . . f f a a a a a a a a a f . . 
                    . . f a a f f f f f f a a f . . 
                    . . f f f f a a a a f f f f . . 
                    . f f a f b f 4 4 f b f a f f . 
                    . f a a 4 1 f d d f 1 4 a a f . 
                    . . f a a d d d d d d a a a . . 
                    . . . f a a 4 4 4 4 a a f . . . 
                    . . 5 5 f a a a a a a f 5 5 . . 
                    . . 5 5 f a a a a a a f 5 5 . . 
                    . . 5 5 f 5 5 5 5 5 5 f 5 5 . . 
                    . . . . . f f f f f f . . . . . 
                    . . . . . f f . . f f . . . . .
        """),
        SpriteKind.dougenentrence)
    tiles.place_on_tile(doungenentrence, tiles.get_tile_location(5, 1))

def on_overlap_tile4(sprite8, location4):
    global Firstenemy, numbercounter
    if numbercounter == 1:
        Firstenemy = sprites.create(img("""
                ........................
                            ........................
                            ........................
                            ........................
                            ..........fffff.........
                            ........ff11111f........
                            .......fb111111bf.......
                            ......fbd1111111f.......
                            ......fddd111111df......
                            ......fdddd11111df......
                            ......fddddddd11df......
                            ......fddddddd111f......
                            ......fddddddcf11f......
                            .......fbdddb1111bf.....
                            ........fffcfdb1b1f.....
                            .......ffffffffbfbf.....
                            ....ff.fffffffffff......
                            .....ffffffff...........
                            .....ffffffb1b1f........
                            ......ffffffbfbf........
                            ........................
                            ........................
                            ........................
                            ........................
            """),
            SpriteKind.enemy)
        Firstenemy.follow(sprite8, 500)
        scene.camera_shake(4, 3000)
        game.show_long_text("Fear from my power", DialogLayout.BOTTOM)
        numbercounter = numbercounter + 1
    tiles.place_on_tile(Firstenemy, tiles.get_tile_location(9, 5))
scene.on_overlap_tile(SpriteKind.empoweredPlayer,
    sprites.dungeon.dark_ground_east,
    on_overlap_tile4)

def fireCommanSpell1():
    global projectilefire
    animation.run_image_animation(firewizard,
        [img("""
                ......ffff..............
                        ....fff22fff............
                        ...fff2222fff...........
                        ..fff222222fff..........
                        ..ff222222222f..........
                        ..f22ffffff22f..........
                        ..ffffeeeeffff..........
                        .ffefbf44fbfeff.........
                        .fee41fddf14eef.........
                        .ffeeddddddeeff2........
                        2..fee4444eef..2........
                        2222f222222f2222........
                        2222f222222f2222........
                        ....f225522f22..........
                        .....ffffff.............
                        .....ff..ff.............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ..............ffffff....
                        .............f2feeeeff..
                        ............f222feeeeff.
                        .......cc...f222effeeef.
                        .......c2c.f22222eeffff.
                        .......c22cf22ffff222ef.
                        ........c44cffeeefffffff
                        .........c44c244fbe44eff
                        ..........c4c2ddf14d4eef
                        ..........ccc2eddd4eeef.
                        ...........2222e44eeff..
                        ............22222222f...
                        .............f2eeeeef...
                        .............f554444f...
                        ..............ffffff....
                        ................fff.....
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ..............fff.......
                        .............f2fffff....
                        ...........ff2222222ff..
                        ..........ff222222222ff.
                        ..........f2222fff2222f.
                        .........f22222222fffff.
                        .........f22fffff2222fff
                        ..cc.....fffeeefffffffff
                        ..c2cc...fee44fbbe44efef
                        ..cc24cc..feddfbb4d4eef.
                        ....c444c2efddddd4eeef..
                        .....cc4c22ee2222222f...
                        ......ccc2244e544444f...
                        .........22eeffffffff...
                        .............ff...fff...
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ...............ff.......
                        .............ff2ffff....
                        ............ff2f2222ff..
                        ...........ff22f22222ff.
                        ...........f2222ff2222f.
                        ..........f2222222fffff.
                        ..........f22ffff2222fff
                        ..........fffeeeffffffff
                        ..........fee44fbe44efef
                        ...........feddfb4d4eef.
                        ..........c.eeddd4eeef..
                        ....ccccccceddee2222f...
                        ....222444cedd44e444f...
                        ......ccccc.eeeefffff...
                        ..........c...ffffffff..
                        ...............ff..fff..
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ..............fff.......
                        .............f2fffff....
                        ...........ff2222222ff..
                        ..........ff222222222ff.
                        ..........f2222fff2222f.
                        .........f22222222fffff.
                        .........f22fffff2222fff
                        ..cc.....fffeeefffffffff
                        ..c2cc...fee44fbbe44efef
                        ..cc22cc..feddfbb4d4eef.
                        ....c444c22fddddd4eeef..
                        .....cc4c22ee2222222f...
                        ......ccc2244e544444f...
                        .........22eeffffffff...
                        .............ff...fff...
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ..............ffffff....
                        .............f2f22222f..
                        ............f222f2222ff.
                        .......cc...f2222222222.
                        .......c2c.f2222222ffff.
                        .......c22cf22ffff2222f.
                        ........c24cffeeefffffff
                        .........c44ce44fbe44eff
                        ..........c4c2ddf14d4eef
                        ..........ccc2eddd4eeef.
                        ...........2224e44eeff..
                        ............22442222f...
                        .............f2eeeeef...
                        .............f554444f...
                        ..............ffffff....
                        ................fff.....
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ......ffff..............
                        ....fff22fff............
                        ...fff2222fff...........
                        ..fff222222fff..........
                        ..ff222222222f..........
                        ..f22ffffff22f..........
                        ..ffffeeeeffff..........
                        .ffefbf44fbfeff.........
                        .fee41fddf14eef.........
                        .ffeeddddddeeff2........
                        2..fee4444eef..2........
                        2222f222222f2222........
                        2222f222222f2222........
                        ....f225522f22..........
                        .....ffffff.............
                        .....ff..ff.............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """)],
        200,
        False)
    pause(500)
    projectilefire = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . 2 2 2 2 2 2 2 2 2 2 2 . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        firewizard,
        -100,
        0)
def icewizard2():
    global icewizard
    icewizard = sprites.create(img("""
            . . . . . . f f f f . . . . . . 
                    . . . . f f f 9 9 f f f . . . . 
                    . . . f f f 9 9 9 9 f f f . . . 
                    . . f f f 9 9 9 9 9 9 f f f . . 
                    . . f f 9 9 9 9 9 9 9 9 9 f . . 
                    . . f 9 9 f f f f f f 9 9 f . . 
                    . . f f f f e e e e f f f f . . 
                    . f f e f b f 4 4 f b f e f f . 
                    . f e e 4 1 f d d f 1 4 e e f . 
                    . . f e e d d d d d d e e f . . 
                    9 . . f e e 4 4 4 4 e e f . . . 
                    9 9 9 9 f 8 8 8 8 8 8 f 9 9 . . 
                    9 9 9 9 f 8 8 8 8 8 8 f 9 9 . . 
                    . . . . f 8 8 5 5 8 8 f 9 9 9 . 
                    . . . . . f f f f f f . . . 9 9 
                    . . . . . f f . . f f . . . . 9
        """),
        SpriteKind.empoweredPlayer)
    spriteController(icewizard)

def on_overlap_tile5(sprite9, location5):
    spriteCreator("fire")
    afterpower(firewizard)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_red_crystal,
    on_overlap_tile5)

def on_overlap_tile6(sprite10, location6):
    spriteCreator("ice")
    afterpower(icewizard)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_insignia,
    on_overlap_tile6)

def iceCommonSpell1():
    global projectileice
    animation.run_image_animation(icewizard,
        [img("""
                ........................
                        ........................
                        ........................
                        ..........ffff..........
                        ........fff99fff........
                        .......fff9999fff.......
                        ......fff999999fff......
                        ......ff999999999f......
                        ......f99ffffff99f......
                        ......ffffeeeeffff......
                        .....ffefbf44fbfeff.....
                        .....fee41fddf14eef.....
                        .....ffeeddddddeeff.....
                        ....9..fee4444eef.......
                        ....9999f888888f99......
                        ....9999f888888f99......
                        ........f885588f999.....
                        .........ffffff...99....
                        .........ff..ff....9....
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        .........ffffff.........
                        ........f9f9999ff.......
                        .......f99999999ff......
                        ..cc...f9999ff999f......
                        ..c9c.f9999999ffff......
                        ..c99cf99ffff9999f......
                        ...c99cffeeefffffff.....
                        ....c88c444fbe44eff.....
                        .....c8c4ddf14d4eef.....
                        .....ccc4eddd4eeef......
                        ......8888e44eeff.......
                        .......88888888f........
                        ........f888888f........
                        ........f888888f........
                        .........ffffff.........
                        ...........fff..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........fff..........
                        ..........f9fffff.......
                        ........ff9999999ff.....
                        .......ff999999999ff....
                        .......f9999fff9999f....
                        ......f99999999fffff....
                        ......f99fffff9999fff...
                        c.....fffeeefffffffff...
                        9cc...fee44fbbe44efef...
                        c98cc..feddfbb4d4eef....
                        .c888c888888888888f.....
                        ..c88c88888888888f......
                        ...ccc88888888888f......
                        ......8888ffffffff......
                        ..........ff...fff......
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ...............ff.......
                        .............ff9ffff....
                        ............ff9f9999ff..
                        ...........ff99f99999ff.
                        ...........f9999999999f.
                        ..........f9999999fffff.
                        ..........f99ffff9999fff
                        ..........fffeeeffffffff
                        ..........fee44fbe44efef
                        ...........feddfb4d4eef.
                        ..........c.eeddd4eeef..
                        ....ccccccc888888888f...
                        ....999888c888888888f...
                        ......ccccc.8888fffff...
                        ..........c...ffffffff..
                        ...............ff..fff..
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ...........fff..........
                        ..........f9fffff.......
                        ........ff9999999ff.....
                        .......ff999999999ff....
                        .......f9999fff9999f....
                        ......f99999999fffff....
                        ......f99fffff9999fff...
                        c.....fffeeefffffffff...
                        9cc...fee44fbbe44efef...
                        c98cc..feddfbb4d4eef....
                        .c888c888888888888f.....
                        ..c88c88888888888f......
                        ...ccc88888888888f......
                        ......8888ffffffff......
                        ..........ff...fff......
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        .........ffffff.........
                        ........f9f9999ff.......
                        .......f99999999ff......
                        ..cc...f9999ff999f......
                        ..c9c.f9999999ffff......
                        ..c99cf99ffff9999f......
                        ...c99cffeeefffffff.....
                        ....c88c444fbe44eff.....
                        .....c8c4ddf14d4eef.....
                        .....ccc4eddd4eeef......
                        ......8888e44eeff.......
                        .......88888888f........
                        ........f888888f........
                        ........f888888f........
                        .........ffffff.........
                        ...........fff..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        ........................
                        ........................
                        ..........ffff..........
                        ........fff99fff........
                        .......fff9999fff.......
                        ......fff999999fff......
                        ......ff999999999f......
                        ......f99ffffff99f......
                        ......ffffeeeeffff......
                        .....ffefbf44fbfeff.....
                        .....fee41fddf14eef.....
                        .....ffeeddddddeeff.....
                        ....9..fee4444eef.......
                        ....9999f888888f99......
                        ....9999f888888f99......
                        ........f885588f999.....
                        .........ffffff...99....
                        .........ff..ff....9....
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """)],
        200,
        False)
    pause(500)
    projectileice = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . 9 9 9 9 9 9 9 9 9 9 9 . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        firewizard,
        -100,
        0)
projectileice: Sprite = None
icewizard: Sprite = None
projectilefire: Sprite = None
Firstenemy: Sprite = None
firewizard: Sprite = None
projectileearth: Sprite = None
earthwizard: Sprite = None
doungenentrence: Sprite = None
questionbo_x: Sprite = None
questionbox: Sprite = None
numbercounter = 0
tilemap2: List[tiles.TileMapData] = []
_1st_sprrite: Sprite = None
_1st_sprrite = sprites.create(img("""
        . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . .
    """),
    SpriteKind.player)
tiles.set_current_tilemap(tilemap("""
    level5
"""))
tiles.place_on_random_tile(_1st_sprrite, sprites.builtin.forest_tiles22)
scene.camera_follow_sprite(_1st_sprrite)
controller.move_sprite(_1st_sprrite)
tilemap2 = [tilemap("""
        level1
    """),
    tilemap("""
        level5
    """),
    tilemap("""
        level13
    """),
    tilemap("""
        level27
    """)]
numbercounter = 1