namespace SpriteKind {
    export const question = SpriteKind.create()
    export const question2 = SpriteKind.create()
    export const empoweredPlayer = SpriteKind.create()
    export const dougenentrence = SpriteKind.create()
    export const Boss = SpriteKind.create()
}
namespace StatusBarKind {
    export const BigEnemyy = StatusBarKind.create()
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairNorth, function (sprite, location) {
    questionbox = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e d d d d d d d d d d e e . 
        . e e d f d d d f d f d d e e . 
        . e e f d f d f f f f d d e e . 
        . e e d f d d d f d d d d e e . 
        . e e d f f d f d d d d d e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        `, SpriteKind.question)
    questionbox.setPosition(95, 119)
    questionbo_x = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e d d d d d d d d d d e e . 
        . e e d f d d d f d f d d e e . 
        . e e f d f d f f f f d d e e . 
        . e e d f d d d f d d d d e e . 
        . e e d f f d f d d d d d e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        . e e e e e e e e e e e e e e . 
        `, SpriteKind.question2)
    questionbo_x.setPosition(95, 79)
    tiles.setCurrentTilemap(tilemap2[0])
    tiles.placeOnRandomTile(_1st_sprrite, sprites.dungeon.stairSouth)
})
sprites.onOverlap(SpriteKind.empoweredPlayer, SpriteKind.Boss, function (sprite, otherSprite) {
    color.startFade(color.originalPalette, color.Black, 500)
    tiles.placeOnTile(sprite, tiles.getTileLocation(13, 4))
    tiles.placeOnTile(otherSprite, tiles.getTileLocation(9, 4))
    otherSprite.follow(sprite, 0)
    fightscene12(sprite)
    statusbarSecondEnemy = statusbars.create(20, 4, StatusBarKind.BigEnemyy)
    statusbarSecondEnemy.max = 150
    statusbarSecondEnemy.value = 150
    statusbarSecondEnemy.attachToSprite(SecondEnemy)
    color.startFade(color.Black, color.originalPalette, 500)
    pause(450)
    while (statusbarSecondEnemy.value > 0) {
        if (correctcounter <= 4) {
            QuizAddition2(randint(1, 10), randint(1, 10))
        }
    }
})
sprites.onOverlap(SpriteKind.empoweredPlayer, SpriteKind.dougenentrence, function (sprite, otherSprite) {
    controller.moveSprite(sprite, 0, 0)
    game.showLongText("Greetings! Do you want to go into the hell of dogends", DialogLayout.Bottom)
    story.showPlayerChoices("Yes I am ready", "Give me some time")
    if (story.checkLastAnswer("Yes I am ready")) {
        tiles.setCurrentTilemap(tilemap2[3])
        sprites.destroy(doungenentrence)
        tiles.placeOnTile(sprite, tiles.getTileLocation(19, 5))
    } else {
        game.showLongText("Okay have some time then", DialogLayout.Center)
    }
    controller.moveSprite(sprite, 100, 100)
})
scene.onOverlapTile(SpriteKind.empoweredPlayer, sprites.dungeon.darkGroundWest, function (sprite, location) {
    if (numbercounter == 2) {
        game.showLongText("BEWARE I AM THE STRONGEST", DialogLayout.Bottom)
        pause(200)
        SecondEnemy = sprites.create(img`
            ...................................
            ...................................
            ...................................
            ..............ccc..................
            ..............ccc..................
            ..............ccccc................
            .........ccc...ccccccccc...........
            .........cccccccc5555555ccc........
            .........cccccccc5555555ccc........
            ..........cccb5555555555555c.......
            .......cc...b555555555555555c......
            .......cccbb5555555fff1555555c.....
            .......cccbb5555555fff1555555c.....
            .......ccb5555555555fff55dd55c.....
            ........b55555555555555555555c.....
            ....c...b5555d555555bbb13bbbc......
            ....c...b5555d555555bbb13bbbc......
            ....ccccd555dddddd55bbb33335c......
            .....ccbdddddddddddd555b3335c......
            ...ccccddddddb555bddddd55555c......
            ...ccccddddddb555bddddd55555c......
            ...ccccddddddb5555bbbbbccccc.......
            ....cccdddddddb55555ccbcdcc........
            cccccbbddddddddccb55ccbcc..........
            cccccbbddddddddccb55ccbcc..........
            ccddddddddddd55ddbccbbbc...........
            ccbdddddddddd5555dbbbbcc...........
            ..ccbddddbbbdd5555bbccdbccc........
            ..ccbddddbbbdd5555bbccdbccc........
            ....ccccbbbbbdd555ccddddbcc........
            ........ccccbddddbccccccccc........
            ..........ccdd5555dc...............
            ..........ccdd5555dc...............
            ...................................
            ...................................
            `, SpriteKind.Boss)
        SecondEnemy.follow(sprite, 100)
        scene.cameraShake(4, 3000)
        tiles.placeOnTile(SecondEnemy, tiles.getTileLocation(9, 4))
        numbercounter = numbercounter + 1
    }
})
scene.onOverlapTile(SpriteKind.empoweredPlayer, sprites.dungeon.stairNorth, function (sprite, location) {
    game.showLongText("You may no longer enter", DialogLayout.Center)
    tiles.setWallAt(location, true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.question, function (sprite, otherSprite) {
    controller.moveSprite(sprite, 0, 0)
    game.showLongText("How did you get here?", DialogLayout.Bottom)
    story.showPlayerChoices("I went down the stairs", "Why do you need to know?")
    game.showLongText("Well, you came here at the right time I guess. ", DialogLayout.Bottom)
    game.showLongText("this is a place that you get your super power", DialogLayout.Bottom)
    sprites.destroy(otherSprite)
    controller.moveSprite(sprite, 100, 100)
})
scene.onOverlapTile(SpriteKind.empoweredPlayer, sprites.dungeon.stairWest, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap2[4])
    tiles.placeOnRandomTile(sprite, sprites.dungeon.stairEast)
})
function spriteController (mySprite: Sprite) {
    controller.moveSprite(mySprite)
    scene.cameraFollowSprite(mySprite)
    mySprite.setFlag(SpriteFlag.StayInScreen, true)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.question2, function (sprite, otherSprite) {
    controller.moveSprite(sprite, 0, 0)
    game.showLongText("CHOOSE YOUR POWER", DialogLayout.Bottom)
    story.showPlayerChoices("Fire", "Ice", "Earth")
    if (story.checkLastAnswer("Fire")) {
        tiles.placeOnRandomTile(_1st_sprrite, sprites.dungeon.collectibleRedCrystal)
    } else if (story.checkLastAnswer("Ice")) {
        tiles.placeOnRandomTile(_1st_sprrite, sprites.dungeon.collectibleInsignia)
    } else if (story.checkLastAnswer("Earth")) {
        tiles.placeOnRandomTile(_1st_sprrite, sprites.dungeon.collectibleBlueCrystal)
    }
    controller.moveSprite(sprite, 100, 100)
})
function earthwizard2 () {
    earthwizard = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 7 7 f f f . . . . 
        . . . f f f 7 8 8 7 f f f . . . 
        . . f f f 7 8 7 7 8 7 f f f . . 
        . . f f 7 7 8 7 7 8 7 7 7 f . . 
        . . f 7 7 f f f f f f 7 7 f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . f f e e d d d d d d e e f f 7 
        7 . . f e e 4 4 4 4 e e f . . 7 
        7 7 7 7 f 7 8 8 8 8 7 f 7 7 7 7 
        7 7 7 7 f 7 8 8 8 8 7 f 7 7 7 7 
        . . . . f 7 7 5 5 7 7 f 7 7 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.empoweredPlayer)
    spriteController(earthwizard)
    spritetype = "earth"
}
sprites.onOverlap(SpriteKind.empoweredPlayer, SpriteKind.Enemy, function (sprite, otherSprite) {
    color.startFade(color.originalPalette, color.Black, 500)
    tiles.placeOnTile(sprite, tiles.getTileLocation(10, 5))
    tiles.placeOnTile(otherSprite, tiles.getTileLocation(8, 5))
    otherSprite.follow(sprite, 0)
    fightscene12(sprite)
    statusbarMysprite = statusbars.create(20, 4, StatusBarKind.Health)
    statusbarMysprite.value = 100
    statusbarMysprite.attachToSprite(sprite)
    statusbarFirstEnemy = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
    statusbarFirstEnemy.max = 100
    statusbarFirstEnemy.attachToSprite(otherSprite)
    color.startFade(color.Black, color.originalPalette, 500)
    pause(450)
    while (statusbarFirstEnemy.value > 0) {
        if (correctcounter <= 2) {
            QuizAddition(randint(1, 10), randint(1, 10))
        }
    }
})
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    sprites.destroy(Firstenemy)
    controller.moveSprite(firewizard)
    controller.moveSprite(earthwizard)
    controller.moveSprite(icewizard)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleBlueCrystal, function (sprite, location) {
    spriteCreator("earth")
    afterpower(earthwizard)
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.gameOver(false)
})
function spriteCreator (text: string) {
    if (text == "fire") {
        firewizard2()
    } else if (text == "ice") {
        icewizard2()
    } else {
        earthwizard2()
    }
}
statusbars.onZero(StatusBarKind.BigEnemyy, function (status) {
    sprites.destroy(SecondEnemy, effects.fire, 1000)
    pause(500)
    game.gameOver(true)
})
function fightscene12 (mySprite: Sprite) {
    tiles.placeOnTile(mySprite, tiles.getTileLocation(13, 5))
    controller.moveSprite(mySprite, 0, 0)
    tiles.placeOnTile(Firstenemy, tiles.getTileLocation(9, 5))
    Firstenemy.follow(mySprite, 0)
}
function firewizard2 () {
    firewizard = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f 2 2 2 2 2 2 f f f . . 
        . . f f 2 2 2 2 2 2 2 2 2 f . . 
        . . f 2 2 f f f f f f 2 2 f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . f f e e d d d d d d e e f f 2 
        2 . . f e e 4 4 4 4 e e f . . 2 
        2 2 2 2 f 2 2 2 2 2 2 f 2 2 2 2 
        2 2 2 2 f 2 2 2 2 2 2 f 2 2 2 2 
        . . . . f 2 2 5 5 2 2 f 2 2 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.empoweredPlayer)
    spriteController(firewizard)
    spritetype = "fire"
}
function earthCommonSpell1 () {
    animation.runImageAnimation(
    earthwizard,
    [img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........fff77fff........
        .......fff7887fff.......
        ......fff787787fff......
        ......ff778778777f......
        ......f77ffffff77f......
        ......ffffeeeeffff......
        .....ffefbf44fbfeff.....
        .....fee41fddf14eef.....
        .....ffeeddddddeeff7....
        ....7..fee4444eef..7....
        ....7777f788887f7777....
        ....7777f788887f7777....
        ........f775577f77......
        .........ffffff.........
        .........ff..ff.........
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        .........ffffff.........
        ........f7f7777ff.......
        .......f77777777ff......
        ..cc...f7877f8777f......
        ..c7c.f7788888ffff......
        ..c77cf77ffff7777f......
        ...c77cffeeefffffff.....
        ....c88c444fbe44eff.....
        .....c8c4ddf14d4eef.....
        .....ccc4eddd4eeef......
        ......8888e44eeff.......
        .......88888888f........
        ........f878887f........
        ........f877777f........
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ...........fff..........
        ..........f7fffff.......
        ........ff7777777ff.....
        .......ff787778777ff....
        .......f77888887777f....
        ......f77777777fffff....
        ......f77fffff7777fff...
        c.....fffeeefffffffff...
        7cc...fee44fbbe44efef...
        c78cc..feddfbb4d4eef....
        .c888c888888888888f.....
        ..c88c88887888878f......
        ...ccc88887777778f......
        ......8888ffffffff......
        ..........ff...fff......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ...............ff.......
        .............ff7ffff....
        ............ff7f7777ff..
        ...........ff77f77777ff.
        ...........f7777777777f.
        ..........f7777777fffff.
        ..........f77ffff7777fff
        ..........fffeeeffffffff
        ..........fee44fbe44efef
        ...........feddfb4d4eef.
        ..........c.eeddd4eeef..
        ....ccccccc888788878f...
        ....777888c888777778f...
        ......ccccc.8888fffff...
        ..........c...ffffffff..
        ...............ff..fff..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ...........fff..........
        ..........f7fffff.......
        ........ff7777777ff.....
        .......ff777777777ff....
        .......f7777fff7777f....
        ......f77777777fffff....
        ......f77fffff7777fff...
        c.....fffeeefffffffff...
        7cc...fee44fbbe44efef...
        c78cc..feddfbb4d4eef....
        .c888c888888888888f.....
        ..c88c88878888878f......
        ...ccc88877777778f......
        ......8888ffffffff......
        ..........ff...fff......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        .........ffffff.........
        ........f7f7777ff.......
        .......f77777777ff......
        ..cc...f787778777f......
        ..c7c.f7788888ffff......
        ..c77cf77ffff7777f......
        ...c77cffeeefffffff.....
        ....c88c444fbe44eff.....
        .....c8c4ddf14d4eef.....
        .....ccc4eddd4eeef......
        ......8888e44eeff.......
        .......88888888f........
        ........f878878f........
        ........f877778f........
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........fff77fff........
        .......fff7887fff.......
        ......fff787787fff......
        ......ff778778777f......
        ......f77ffffff77f......
        ......ffffeeeeffff......
        .....ffefbf44fbfeff.....
        .....fee41fddf14eef.....
        .....ffeeddddddeeff7....
        ....7..fee4444eef..7....
        ....7777f788887f7777....
        ....7777f788887f7777....
        ........f775577f77......
        .........ffffff.........
        .........ff..ff.........
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
    pause(500)
    earthprojectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 7 7 7 7 7 7 7 7 . . . . 
        . . . 7 8 8 8 8 8 8 8 8 7 . . . 
        . . . . 7 7 7 7 7 7 7 7 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, earthwizard, -100, 0)
    pause(500)
    sprites.destroy(earthprojectile)
}
function QuizAddition2 (num1: number, num2: number) {
    addition1 = game.askForNumber("" + num1 + " + " + num2, 2)
    if (addition1 == num1 + num2) {
        game.splash("Correct Answer!!")
        if (spritetype == "fire") {
            fireCommanSpell1()
        } else if (spritetype == "ice") {
            iceCommonSpell1()
        } else {
            earthCommonSpell1()
        }
        pause(200)
        if (correctcounter >= 0) {
            pause(200)
            for (let index = 0; index < 2; index++) {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 4 5 4 5 4 4 4 4 5 . . 
                    5 4 4 4 5 5 5 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 5 4 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, Firstenemy, 0, -50)
                pause(500)
                statusbarSecondEnemy.value += -25
            }
            pause(250)
            correctcounter += 1
            sprites.destroy(damagecoin1)
        }
    } else {
        game.splash("Wrong Answer!")
        pause(200)
        animation.runImageAnimation(
        SecondEnemy,
        [img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...............cccc................
            ...............cccc................
            ...............ccccc...............
            .........cccc...cccccccccc.........
            .........cccccccc555555555cc.......
            .........cccccccc555555555cc.......
            ..........cccbb5555555555555cc.....
            ......ccc...b55555555555555555c....
            ......ccccbb55555555fff15555555c...
            ......ccccbb55555555fff15555555c...
            ........cb55555555555fff555d555c...
            ........b5555555555555555555555c...
            ....cc..b5555ddd55555bbb113bbbc....
            ....cc..b5555ddd55555bbb113bbbc....
            ....ccccd555ddddddd5555b333355c....
            ......bbddddddddddddd555bb3355c....
            ......bbddddddddddddd555bb3355c....
            ..ccccdddddddbb55bbbdddd555555c....
            ..ccccdddddddbb5555bbbbbcccccc.....
            ....ccdddddddddb55555ccbccdc.......
            ....ccdddddddddb55555ccbccdc.......
            cccccbddddddddd5cbb55ccbccc........
            cdddddddddddd555555ccbbbcc.........
            .cddddddddbbddd5555bbbbccc.........
            .cddddddddbbddd5555bbbbccc.........
            ..cccddddbbbbddd555cbccdcc.........
            .....cccbbccbddddddccdddddcc.......
            ........ccccddd5555dcccccccc.......
            ........ccccddd5555dcccccccc.......
            ..........ccccccccccc..............
            `,img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            .............cccc..................
            .............cccc..................
            .............cccccccccc............
            .........cc...ccc555555ccc.........
            .........ccccc555555555555c........
            .........ccbb55555555555555cc......
            .....cc...b5555555fff15555555c.....
            .....cc...b5555555fff15555555c.....
            .....ccccb555555555fff555d555c.....
            ......cccb5555555d55555555555c.....
            .......bb555555dd55555d555555c.....
            ...ccc.bb5555dddd555555bbbbbbc.....
            ...ccccdd55ddddddd55555dd5555c.....
            ...ccccdd55ddddddd55555dd5555c.....
            .....ccddd5ddbddddbbbbd5555cc......
            ......bddddbb5555bbbbbbcccc........
            ...ccccddddbb5555cbbbbbbbbc........
            .....ccddddddb5555cbbbbbbbbcc......
            ......cdddddddb5555ccbbbbbbcc......
            ......cdddddddb5555ccbbbbbbcc......
            .....ccddddddddbb55ccbbbbbbccc.....
            ...cccbddddddd555bcbbbbbbbbccc.....
            cccddddddddddd55555bbbbbbbbcc......
            ccdddddddddbbdd5555bbbbbbbc........
            ..cccdddddbbbbddd55ccbbcccc........
            ..cccdddddbbbbddd55ccbbcccc........
            .....ccccbbccbdddddcccddddccc......
            .........ccccdd5555ddcccccccc......
            ...........ccccccccccc.............
            `,img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...........cccc....................
            ...........cccc....................
            ...........ccccccccccc.............
            .......ccc..ccc5555555cc...........
            .......ccccc555555555555cc.........
            .......cccb555555555555555c........
            .......cccb555555555555555c........
            ....ccc.bb55555bccc55555555c.......
            ....cccb55555555555c555d555c.......
            ......cb555555dd55555555555c.......
            .......55555ddd55555dd55555c.......
            .......55555ddd55555dd55555c.......
            ...ccc.5555ddd55555555dbbbbc.......
            ...cccc555dddd55555555d5555c.......
            ....cccd55dbddd55555dd5555c........
            ......bddddb5555bbbbbbbcccc........
            ......bddddb5555bbbbbbbcccc........
            ...ccccddddb5555ccbbbbbbbbbc.......
            ....cccdddddbb5555cbbbbbbbbbcc.....
            ......cdddddddb5555cbbbbbbbbcc.....
            ....cccddddddddb555cbbbbbbbbccc....
            ....cccddddddddb555cbbbbbbbbccc....
            ....ccbddddddd55bbcbbbbbbbbbccc....
            ...cbbdddddddd55555bbbbbbbbbcc.....
            ..cddddddddbddd5555bbbbbbbbc.......
            ccddddddddbbbbdd555cbbbcccc........
            ccddddddddbbbbdd555cbbbcccc........
            ccccccccbbbcbbdddddcccddddcc.......
            ........ccccddd5555dcccccccc.......
            ...........ccccccccccc.............
            `,img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ..............cccc.................
            ..............ccccc................
            .........cccc..ccccccccc...........
            .........cccccccc5555555ccc........
            ..........cccb5555555555555c.......
            ..........cccb5555555555555c.......
            .......cc...b555555555555555c......
            .......cccbb555555bccc5555555c.....
            ........cb555555555555c55dd55c.....
            ........b55555555555555555555c.....
            ....ccc.b5555dd55555bbb1bbbbc......
            ....ccc.b5555dd55555bbb1bbbbc......
            .....cccd555dddddd5bbbbb3335c......
            ....cccbdddddddddd5bbbbb3335c......
            ..cccccddddddddddd55bbbb3335c......
            ccdccccddddddb555bb5bbb33335c......
            ccddbddddddddb5555bb55b33335c......
            ccddbddddddddb5555bb55b33335c......
            ccddddddddddddb55555bb533335c......
            cccdddddddbbd55bbb55cc55555c.......
            ..ccdddddbbbbdd555ccccbcccc........
            ....cccbbbccbdddddccddddc..........
            .......cccccdd5555dcccccc..........
            .......cccccdd5555dcccccc..........
            ..........cccccccccc...............
            `,img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...............ccc.................
            ...............ccccc...............
            .........cccc...ccccccccc..........
            .........cccccccc55555555cc........
            ...........ccbb555555555555cc......
            ...........ccbb555555555555cc......
            .......cc...b5555555555555555c.....
            .......ccccb555555bbcc55555555c....
            ........cbb55555555555cc55d555c....
            ........b555555555555555555555c....
            ....ccc.b5555ddd55555bbb1bbbbc.....
            ....ccc.b5555ddd55555bbb1bbbbc.....
            ......ccd555dddddd55bbbbb3355c.....
            ....cccbdddddddddd55bbbbb3355c.....
            ..cccccddddddddddd555bbb33355c.....
            ccdccccddddddbb55bbb55bb33355c.....
            ccddbbdddddddbb555bbb55533355c.....
            ccdddddddddddddb55555b55555cc......
            ccdddddddddddddb55555b55555cc......
            cccddddddddbd555bb555cbbccc........
            ..ccdddddbbbbddd55cccbbbc..........
            ....cccbbbbcbdddddcccddddc.........
            .......cccccddd555ddcccccc.........
            ...........cccccccccc..............
            ...........cccccccccc..............
            `,img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            .............cccc..................
            .............ccccc.................
            ........cccc..ccccccccc............
            ........cccccccc5555555cc..........
            .........cccb555555555555cc........
            .........cccb555555555555cc........
            ......cc...b555555555555555c.......
            ......cccbb555555bcc55555555c......
            .......cb55555555555cc55d555c......
            .......b55555555555555555555c......
            ...ccc.b5555dd55555bbb1bbbbc.......
            ...ccc.b5555dd55555bbb1bbbbc.......
            ....cccd555dddddd55bbbb3355c.......
            ...cccbddddddddddd5bbb33355c.......
            .cccccdddddddddddd55bb33355c.......
            cdccccddddddb555bbd55533355c.......
            cddbddddddddb5555bb555555cc........
            cddddddddddddb55555bbbccc..........
            cddddddddddddb55555bbbccc..........
            ccdddddddbbd55bbb55cbbc............
            .ccdddddbbbbdd555ccbddc............
            ...cccbbbccbdddddccddddc...........
            ......cccccdd5555dcccccc...........
            .........cccccccccc................
            .........cccccccccc................
            `,img`
            ...................................
            ...................................
            ...................................
            ...................................
            ...................................
            ...............cccc................
            ...............cccc................
            ...............ccccc...............
            .........cccc...cccccccccc.........
            .........cccccccc555555555cc.......
            .........cccccccc555555555cc.......
            ..........cccbb5555555555555cc.....
            ......ccc...b55555555555555555c....
            ......ccccbb55555555fff15555555c...
            ......ccccbb55555555fff15555555c...
            ........cb55555555555fff555d555c...
            ........b5555555555555555555555c...
            ....cc..b5555ddd55555bbb113bbbc....
            ....cc..b5555ddd55555bbb113bbbc....
            ....ccccd555ddddddd5555b333355c....
            ......bbddddddddddddd555bb3355c....
            ......bbddddddddddddd555bb3355c....
            ..ccccdddddddbb55bbbdddd555555c....
            ..ccccdddddddbb5555bbbbbcccccc.....
            ....ccdddddddddb55555ccbccdc.......
            ....ccdddddddddb55555ccbccdc.......
            cccccbddddddddd5cbb55ccbccc........
            cdddddddddddd555555ccbbbcc.........
            .cddddddddbbddd5555bbbbccc.........
            .cddddddddbbddd5555bbbbccc.........
            ..cccddddbbbbddd555cbccdcc.........
            .....cccbbccbddddddccdddddcc.......
            ........ccccddd5555dcccccccc.......
            ........ccccddd5555dcccccccc.......
            ..........ccccccccccc..............
            `],
        100,
        false
        )
        secondEnemyDamage = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . 5 5 5 5 7 7 5 5 5 5 7 . . 
            . . . 5 2 2 2 2 2 2 2 2 2 5 . . 
            . . . 7 2 2 2 2 2 2 2 2 2 5 . . 
            . . . 5 5 5 7 7 5 5 5 5 7 5 . . 
            `, SecondEnemy, 100, 0)
        for (let index = 0; index < 2; index++) {
            pause(500)
            if (spritetype == "ice") {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 4 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 5 4 4 5 4 4 4 4 5 . . 
                    5 4 4 4 4 5 4 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 4 5 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, icewizard, 0, -50)
            } else if (spritetype == "fire") {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 4 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 5 4 4 5 4 4 4 4 5 . . 
                    5 4 4 4 4 5 4 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 4 5 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, firewizard, 0, -50)
            } else if (spritetype == "earth") {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 4 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 5 4 4 5 4 4 4 4 5 . . 
                    5 4 4 4 4 5 4 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 4 5 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, earthwizard, 0, -50)
            }
            sprites.destroy(secondEnemyDamage)
            statusbarMysprite.value += -15
        }
        pause(1000)
    }
}
function QuizAddition (num1: number, num2: number) {
    addition1 = game.askForNumber("" + num1 + " + " + num2, 2)
    if (addition1 == num1 + num2) {
        game.splash("Correct Answer!!")
        if (spritetype == "fire") {
            fireCommanSpell1()
        } else if (spritetype == "ice") {
            iceCommonSpell1()
        } else {
            earthCommonSpell1()
        }
        pause(200)
        if (correctcounter >= 0) {
            pause(200)
            for (let index = 0; index < 2; index++) {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 4 5 4 5 4 4 4 4 5 . . 
                    5 4 4 4 5 5 5 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 5 4 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, Firstenemy, 0, -50)
                pause(500)
                statusbarFirstEnemy.value += -25
            }
            pause(250)
            correctcounter += 1
            sprites.destroy(damagecoin1)
        }
    } else {
        game.splash("Wrong Answer!")
        pause(200)
        animation.runImageAnimation(
        Firstenemy,
        [img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fdddddd111df......
            ......fbddddddd1df......
            ......ffbbddbfd1df......
            .......fcbbdcfddbf......
            .......fffbddccffff.....
            .......ffffcfbbb1bcf....
            ......ffffffffcd1b1f....
            ...ffffffffff..fdfdf....
            .....ffffff.....f.f.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            ........................
            ........................
            .........fffff..........
            .......ffb1111ff........
            ......fb1111111bf.......
            ......f111111111f.......
            .....ffff1111111df......
            ....fb111c1dd111df......
            ....ffb1b1fdcf11bf......
            .....ffbfbfb11111f......
            ......ffffcfdb1b1f......
            .......fcccfcfbfbf......
            ........ffffffffff......
            .........ffffff.........
            .........ffffff.........
            .....f..fffffff.........
            .....fffffffff..........
            ......fffffff...........
            ........................
            ........................
            ........................
            ........................
            `],
        100,
        false
        )
        FirstEnemyDamage = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . f f f f f f f f f f f . . . 
            . . f f f f f f f f f f f . . . 
            . . f f f f f f f f f f f . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, Firstenemy, 100, 0)
        for (let index = 0; index < 2; index++) {
            pause(500)
            if (spritetype == "ice") {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 4 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 5 4 4 5 4 4 4 4 5 . . 
                    5 4 4 4 4 5 4 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 4 5 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, icewizard, 0, -50)
            } else if (spritetype == "fire") {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 4 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 5 4 4 5 4 4 4 4 5 . . 
                    5 4 4 4 4 5 4 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 4 5 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, firewizard, 0, -50)
            } else if (spritetype == "earth") {
                damagecoin1 = sprites.createProjectileFromSprite(img`
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . 5 4 5 5 4 4 5 5 5 4 5 . . . 
                    . 5 4 4 4 5 4 4 5 4 4 4 4 5 . . 
                    5 4 4 4 4 5 4 4 5 5 5 4 4 4 5 . 
                    . 5 4 4 4 5 4 4 4 4 5 4 4 5 . . 
                    . . 5 4 5 5 5 4 5 5 5 4 5 . . . 
                    . . . 5 4 4 4 4 4 4 4 5 . . . . 
                    . . . . 5 4 4 4 4 4 5 . . . . . 
                    . . . . . 5 4 4 4 5 . . . . . . 
                    . . . . . . 5 4 5 . . . . . . . 
                    . . . . . . . 5 . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `, earthwizard, 0, -50)
            }
            sprites.destroy(FirstEnemyDamage)
            statusbarMysprite.value += -15
        }
        pause(1000)
    }
}
function afterpower (mySprite: Sprite) {
    sprites.destroy(_1st_sprrite)
    sprites.destroy(questionbo_x)
    sprites.destroy(questionbox)
    tiles.setCurrentTilemap(tilemap2[2])
    tiles.placeOnTile(mySprite, tiles.getTileLocation(5, 9))
    doungenentrence = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f a a f f f . . . . 
        . . . f f f a a a a f f f . . . 
        . . f f f a a a a a a a f f . . 
        . . f f a a a a a a a a a f . . 
        . . f a a f f f f f f a a f . . 
        . . f f f f a a a a f f f f . . 
        . f f a f b f 4 4 f b f a f f . 
        . f a a 4 1 f d d f 1 4 a a f . 
        . . f a a d d d d d d a a a . . 
        . . . f a a 4 4 4 4 a a f . . . 
        . . 5 5 f a a a a a a f 5 5 . . 
        . . 5 5 f a a a a a a f 5 5 . . 
        . . 5 5 f 5 5 5 5 5 5 f 5 5 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.dougenentrence)
    tiles.placeOnTile(doungenentrence, tiles.getTileLocation(5, 1))
}
scene.onOverlapTile(SpriteKind.empoweredPlayer, sprites.dungeon.darkGroundEast, function (sprite, location) {
    if (numbercounter == 1) {
        Firstenemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........fffff.........
            ........ff11111f........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fddd111111df......
            ......fdddd11111df......
            ......fddddddd11df......
            ......fddddddd111f......
            ......fddddddcf11f......
            .......fbdddb1111bf.....
            ........fffcfdb1b1f.....
            .......ffffffffbfbf.....
            ....ff.fffffffffff......
            .....ffffffff...........
            .....ffffffb1b1f........
            ......ffffffbfbf........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        Firstenemy.follow(sprite, 9099999)
        scene.cameraShake(4, 3000)
        game.showLongText("Fear from my power", DialogLayout.Bottom)
        numbercounter = numbercounter + 1
    }
})
function fireCommanSpell1 () {
    animation.runImageAnimation(
    firewizard,
    [img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fff222222fff..........
        ..ff222222222f..........
        ..f22ffffff22f..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        .ffeeddddddeeff2........
        2..fee4444eef..2........
        2222f222222f2222........
        2222f222222f2222........
        ....f225522f22..........
        .....ffffff.............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..............ffffff....
        .............f2feeeeff..
        ............f222feeeeff.
        .......cc...f222effeeef.
        .......c2c.f22222eeffff.
        .......c22cf22ffff222ef.
        ........c44cffeeefffffff
        .........c44c244fbe44eff
        ..........c4c2ddf14d4eef
        ..........ccc2eddd4eeef.
        ...........2222e44eeff..
        ............22222222f...
        .............f2eeeeef...
        .............f554444f...
        ..............ffffff....
        ................fff.....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ..............fff.......
        .............f2fffff....
        ...........ff2222222ff..
        ..........ff222222222ff.
        ..........f2222fff2222f.
        .........f22222222fffff.
        .........f22fffff2222fff
        ..cc.....fffeeefffffffff
        ..c2cc...fee44fbbe44efef
        ..cc24cc..feddfbb4d4eef.
        ....c444c2efddddd4eeef..
        .....cc4c22ee2222222f...
        ......ccc2244e544444f...
        .........22eeffffffff...
        .............ff...fff...
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ...............ff.......
        .............ff2ffff....
        ............ff2f2222ff..
        ...........ff22f22222ff.
        ...........f2222ff2222f.
        ..........f2222222fffff.
        ..........f22ffff2222fff
        ..........fffeeeffffffff
        ..........fee44fbe44efef
        ...........feddfb4d4eef.
        ..........c.eeddd4eeef..
        ....ccccccceddee2222f...
        ....222444cedd44e444f...
        ......ccccc.eeeefffff...
        ..........c...ffffffff..
        ...............ff..fff..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ..............fff.......
        .............f2fffff....
        ...........ff2222222ff..
        ..........ff222222222ff.
        ..........f2222fff2222f.
        .........f22222222fffff.
        .........f22fffff2222fff
        ..cc.....fffeeefffffffff
        ..c2cc...fee44fbbe44efef
        ..cc22cc..feddfbb4d4eef.
        ....c444c22fddddd4eeef..
        .....cc4c22ee2222222f...
        ......ccc2244e544444f...
        .........22eeffffffff...
        .............ff...fff...
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..............ffffff....
        .............f2f22222f..
        ............f222f2222ff.
        .......cc...f2222222222.
        .......c2c.f2222222ffff.
        .......c22cf22ffff2222f.
        ........c24cffeeefffffff
        .........c44ce44fbe44eff
        ..........c4c2ddf14d4eef
        ..........ccc2eddd4eeef.
        ...........2224e44eeff..
        ............22442222f...
        .............f2eeeeef...
        .............f554444f...
        ..............ffffff....
        ................fff.....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fff222222fff..........
        ..ff222222222f..........
        ..f22ffffff22f..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        .ffeeddddddeeff2........
        2..fee4444eef..2........
        2222f222222f2222........
        2222f222222f2222........
        ....f225522f22..........
        .....ffffff.............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
    pause(500)
    fireprojectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 2 2 2 2 2 2 2 2 . . . . 
        . . . 2 4 4 4 4 4 4 4 4 2 . . . 
        . . . . 2 2 2 2 2 2 2 2 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, firewizard, -100, 0)
    pause(500)
    sprites.destroy(fireprojectile)
}
function icewizard2 () {
    icewizard = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 9 9 f f f . . . . 
        . . . f f f 9 9 9 9 f f f . . . 
        . . f f f 9 9 9 9 9 9 f f f . . 
        . . f f 9 9 9 9 9 9 9 9 9 f . . 
        . . f 9 9 f f f f f f 9 9 f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        9 . . f e e 4 4 4 4 e e f . . . 
        9 9 9 9 f 8 8 8 8 8 8 f 9 9 . . 
        9 9 9 9 f 8 8 8 8 8 8 f 9 9 . . 
        . . . . f 8 8 5 5 8 8 f 9 9 9 . 
        . . . . . f f f f f f . . . 9 9 
        . . . . . f f . . f f . . . . 9 
        `, SpriteKind.empoweredPlayer)
    spriteController(icewizard)
    spritetype = "ice"
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite, location) {
    spriteCreator("fire")
    afterpower(firewizard)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleInsignia, function (sprite, location) {
    spriteCreator("ice")
    afterpower(icewizard)
})
function iceCommonSpell1 () {
    animation.runImageAnimation(
    icewizard,
    [img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........fff99fff........
        .......fff9999fff.......
        ......fff999999fff......
        ......ff999999999f......
        ......f99ffffff99f......
        ......ffffeeeeffff......
        .....ffefbf44fbfeff.....
        .....fee41fddf14eef.....
        .....ffeeddddddeeff.....
        ....9..fee4444eef.......
        ....9999f888888f99......
        ....9999f888888f99......
        ........f885588f999.....
        .........ffffff...99....
        .........ff..ff....9....
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        .........ffffff.........
        ........f9f9999ff.......
        .......f99999999ff......
        ..cc...f9999ff999f......
        ..c9c.f9999999ffff......
        ..c99cf99ffff9999f......
        ...c99cffeeefffffff.....
        ....c88c444fbe44eff.....
        .....c8c4ddf14d4eef.....
        .....ccc4eddd4eeef......
        ......8888e44eeff.......
        .......88888888f........
        ........f888888f........
        ........f888888f........
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ...........fff..........
        ..........f9fffff.......
        ........ff9999999ff.....
        .......ff999999999ff....
        .......f9999fff9999f....
        ......f99999999fffff....
        ......f99fffff9999fff...
        c.....fffeeefffffffff...
        9cc...fee44fbbe44efef...
        c98cc..feddfbb4d4eef....
        .c888c888888888888f.....
        ..c88c88888888888f......
        ...ccc88888888888f......
        ......8888ffffffff......
        ..........ff...fff......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ...............ff.......
        .............ff9ffff....
        ............ff9f9999ff..
        ...........ff99f99999ff.
        ...........f9999999999f.
        ..........f9999999fffff.
        ..........f99ffff9999fff
        ..........fffeeeffffffff
        ..........fee44fbe44efef
        ...........feddfb4d4eef.
        ..........c.eeddd4eeef..
        ....ccccccc888888888f...
        ....999888c888888888f...
        ......ccccc.8888fffff...
        ..........c...ffffffff..
        ...............ff..fff..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ...........fff..........
        ..........f9fffff.......
        ........ff9999999ff.....
        .......ff999999999ff....
        .......f9999fff9999f....
        ......f99999999fffff....
        ......f99fffff9999fff...
        c.....fffeeefffffffff...
        9cc...fee44fbbe44efef...
        c98cc..feddfbb4d4eef....
        .c888c888888888888f.....
        ..c88c88888888888f......
        ...ccc88888888888f......
        ......8888ffffffff......
        ..........ff...fff......
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        .........ffffff.........
        ........f9f9999ff.......
        .......f99999999ff......
        ..cc...f9999ff999f......
        ..c9c.f9999999ffff......
        ..c99cf99ffff9999f......
        ...c99cffeeefffffff.....
        ....c88c444fbe44eff.....
        .....c8c4ddf14d4eef.....
        .....ccc4eddd4eeef......
        ......8888e44eeff.......
        .......88888888f........
        ........f888888f........
        ........f888888f........
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........fff99fff........
        .......fff9999fff.......
        ......fff999999fff......
        ......ff999999999f......
        ......f99ffffff99f......
        ......ffffeeeeffff......
        .....ffefbf44fbfeff.....
        .....fee41fddf14eef.....
        .....ffeeddddddeeff.....
        ....9..fee4444eef.......
        ....9999f888888f99......
        ....9999f888888f99......
        ........f885588f999.....
        .........ffffff...99....
        .........ff..ff....9....
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
    pause(500)
    iceprojectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 9 9 9 9 9 9 9 9 . . . . 
        . . . 9 8 8 8 8 8 8 8 8 9 . . . 
        . . . . 9 9 9 9 9 9 9 9 . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, icewizard, -100, 0)
    pause(500)
    sprites.destroy(iceprojectile)
}
let iceprojectile: Sprite = null
let fireprojectile: Sprite = null
let FirstEnemyDamage: Sprite = null
let secondEnemyDamage: Sprite = null
let damagecoin1: Sprite = null
let addition1 = 0
let earthprojectile: Sprite = null
let icewizard: Sprite = null
let firewizard: Sprite = null
let Firstenemy: Sprite = null
let statusbarFirstEnemy: StatusBarSprite = null
let statusbarMysprite: StatusBarSprite = null
let spritetype = ""
let earthwizard: Sprite = null
let doungenentrence: Sprite = null
let correctcounter = 0
let SecondEnemy: Sprite = null
let statusbarSecondEnemy: StatusBarSprite = null
let questionbo_x: Sprite = null
let questionbox: Sprite = null
let numbercounter = 0
let tilemap2: tiles.TileMapData[] = []
let _1st_sprrite: Sprite = null
_1st_sprrite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
tiles.setCurrentTilemap(tilemap`level5`)
tiles.placeOnRandomTile(_1st_sprrite, sprites.builtin.forestTiles22)
scene.cameraFollowSprite(_1st_sprrite)
controller.moveSprite(_1st_sprrite, 100, 100)
tilemap2 = [
tilemap`level1`,
tilemap`level5`,
tilemap`level13`,
tilemap`level27`,
tilemap`level44`
]
numbercounter = 1
